export { FakeVendor } from "./adapters/fake-vendor.ts";
export { FakeWarehouse } from "./adapters/fake-warehouse.ts";
export * from "./db/bookkeeping-repo.ts";
export { openDatabase, transaction, type Db } from "./db/database.ts";
export { listOrderItems, type OrderItem } from "./db/items-repo.ts";
export { getOrder, listOrders, type Order, type OrderStatus } from "./db/orders-repo.ts";
export { listShipments, type Shipment } from "./db/shipments-repo.ts";
export { computeBackoffMs, DEFAULT_BACKOFF, DEFAULT_MAX_ATTEMPTS } from "./dispatcher.ts";
export { createEnvelope, parseEnvelope, type AnyEnvelope, type EventEnvelope } from "./events/envelope.ts";
export { InMemoryQueue } from "./events/queue.ts";
export * from "./events/types.ts";
export { maybeDispatch } from "./fulfillment/dispatch.ts";
export type { FulfillmentRequest, WarehousePort } from "./fulfillment/warehouse.ts";
export { createManualClock, systemClock, type Clock } from "./lib/clock.ts";
export { PermanentError, PipelineError, RetryableError } from "./lib/errors.ts";
export { createLogger, createMemorySink, silentLogger, type Logger } from "./lib/logger.ts";
export { createMetrics, type Metrics } from "./lib/metrics.ts";
export { createPipeline, type Pipeline, type PipelineOptions } from "./pipeline.ts";
export { runReconciliation, type ReconcileReport } from "./reconcile/reconcile.ts";
export type { VendorOrder, VendorSource } from "./reconcile/vendor.ts";
