import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { Config } from "./config.js";

export const WORKFLOW_PATH = ".github/workflows/rafoflow-gate.yml";

type PackageManager = "pnpm" | "npm" | "yarn" | "none";

export function detectPackageManager(root: string): PackageManager {
  if (existsSync(join(root, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(root, "yarn.lock"))) return "yarn";
  if (existsSync(join(root, "package-lock.json"))) return "npm";
  return existsSync(join(root, "package.json")) ? "npm" : "none";
}

export function detectNodeVersion(root: string, fallback: string): string {
  for (const f of [".nvmrc", ".node-version"]) {
    const p = join(root, f);
    if (existsSync(p)) return readFileSync(p, "utf8").trim().replace(/^v/, "");
  }
  return fallback;
}

/** Fingerprint of what the workflow encodes, so `doctor` can tell when it drifted from the config. */
export function gateFingerprint(config: Config, pm: PackageManager, node: string): string {
  const steps = config.gate.map((g) => [g, config.commands[g] ?? ""]);
  return createHash("sha256").update(JSON.stringify({ steps, pm, node })).digest("hex").slice(0, 12);
}

const yamlString = (s: string) => JSON.stringify(s);

/**
 * A GitHub Actions workflow that runs the repo's gate commands on every pull request and on pushes to
 * the default branch. It encodes the commands directly: CI does not need rafoflow installed.
 */
export function renderWorkflow(root: string, config: Config): string {
  const missing = config.gate.filter((g) => !config.commands[g]);
  if (config.gate.length === 0) throw new Error("no gate configured: set `gate:` and `commands:` in .rafoflow/config.yaml");
  if (missing.length) throw new Error(`gate steps without a command: ${missing.join(", ")}`);
  const pm = detectPackageManager(root);
  const node = detectNodeVersion(root, config.ci.node_version);
  const lines = [
    `# Generated by rafoflow from .rafoflow/config.yaml — regenerate with \`rafoflow ci\` after changing the gate.`,
    `# rafoflow-gate-fingerprint: ${gateFingerprint(config, pm, node)}`,
    `name: rafoflow gate`,
    `on:`,
    `  pull_request:`,
    `  push:`,
    `    branches: [main, master]`,
    `permissions:`,
    `  contents: read`,
    `jobs:`,
    `  gate:`,
    `    runs-on: ubuntu-latest`,
    `    steps:`,
    `      - uses: actions/checkout@v4`,
  ];
  if (pm === "pnpm") lines.push(`      - uses: pnpm/action-setup@v4`);
  if (pm !== "none") {
    lines.push(`      - uses: actions/setup-node@v4`, `        with:`, `          node-version: ${yamlString(node)}`);
    if (pm !== "npm" || existsSync(join(root, "package-lock.json"))) lines.push(`          cache: ${pm}`);
    const install = pm === "pnpm" ? "pnpm install --frozen-lockfile" : pm === "yarn" ? "yarn install --frozen-lockfile" : existsSync(join(root, "package-lock.json")) ? "npm ci" : "npm install";
    lines.push(`      - name: install`, `        run: ${yamlString(install)}`);
  }
  for (const g of config.gate) lines.push(`      - name: ${yamlString(`gate: ${g}`)}`, `        run: ${yamlString(config.commands[g]!)}`);
  return lines.join("\n") + "\n";
}

export function writeWorkflow(root: string, config: Config): string {
  const path = join(root, WORKFLOW_PATH);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderWorkflow(root, config));
  return WORKFLOW_PATH;
}

/** "ok" when the workflow encodes the current gate; "stale" when the config changed since; "missing" otherwise. */
export function workflowState(root: string, config: Config): "ok" | "stale" | "missing" {
  const path = join(root, WORKFLOW_PATH);
  if (!existsSync(path)) return "missing";
  const fp = readFileSync(path, "utf8").match(/rafoflow-gate-fingerprint: (\w+)/)?.[1];
  const pm = detectPackageManager(root);
  return fp === gateFingerprint(config, pm, detectNodeVersion(root, config.ci.node_version)) ? "ok" : "stale";
}
