import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentRunner } from "./adapters.js";
import { fill, prompt, schema } from "./assets.js";
import type { Config } from "./config.js";
import { plannerRoute, researcherRoute } from "./routing.js";
import type { Tier } from "./types.js";
import type { Work } from "./work.js";

export interface ResearchOutput {
  answers: { question: string; answer: string; confidence: "high" | "medium" | "low"; evidence: { source: string; level: number; ref: string }[] }[];
  unverified: string[];
  outcome: "done" | "needs_poc" | "blocked";
  open_question: string;
}

export interface PlanOutput {
  direction: string;
  why: string;
  alternatives: { option: string; why_rejected: string }[];
  steps: { action: string; files: string[] }[];
  exit_criteria: string[];
  risks: { risk: string; containment: string }[];
  outcome: "done" | "needs_poc" | "blocked";
  open_question: string;
}

const outcomeLine = (o: { outcome: string; open_question: string }) =>
  `**Outcome:** \`${o.outcome}\`${o.outcome !== "done" && o.open_question ? ` — ${o.open_question}` : ""}`;

export function renderResearch(r: ResearchOutput, at: string): string {
  const out = [`# Research`, "", `Generated by rafoflow on ${at}.`, "", outcomeLine(r), ""];
  r.answers.forEach((a, i) => {
    out.push(`## ${i + 1}. ${a.question}`, "", a.answer, "", `Confidence: ${a.confidence}.`, "");
    if (a.evidence.length) {
      out.push("| Source | Level | Reference |", "| --- | --- | --- |");
      a.evidence.forEach((e) => out.push(`| ${e.source.replaceAll("|", "\\|")} | ${e.level} | ${e.ref.replaceAll("|", "\\|")} |`));
      out.push("");
    }
  });
  out.push("## Not verified", "", ...(r.unverified.length ? r.unverified.map((u) => `- ${u}`) : ["- Nothing reported."]), "");
  return out.join("\n");
}

export function renderPlan(p: PlanOutput, at: string): string {
  const out = [`# Plan`, "", `Generated by rafoflow on ${at}. Needs explicit human approval: \`rafoflow approve plan\`.`, "", outcomeLine(p), ""];
  out.push("## Direction", "", p.direction, "", p.why, "");
  out.push("## Alternatives rejected", "", ...(p.alternatives.length ? p.alternatives.map((a) => `- **${a.option}** — ${a.why_rejected}`) : ["- None considered."]), "");
  out.push("## Steps", "", ...p.steps.map((s, i) => `${i + 1}. ${s.action}${s.files.length ? ` (${s.files.map((f) => `\`${f}\``).join(", ")})` : ""}`), "");
  out.push("## Exit criteria", "", ...p.exit_criteria.map((c) => `- ${c}`), "");
  out.push("## Risks", "", ...(p.risks.length ? p.risks.map((r) => `- **${r.risk}** — ${r.containment}`) : ["- None identified."]), "");
  return out.join("\n");
}

interface RoleDeps {
  config: Config;
  tier: Tier;
  cwd: string;
  work: Work;
  runner: AgentRunner;
}

export function research(d: RoleDeps & { request: string; questions: string[] }): ResearchOutput {
  const route = researcherRoute(d.config, d.tier);
  const res = d.runner({
    label: "researcher",
    prompt: fill(prompt("researcher"), { request: d.request || "(not given)", questions: d.questions.map((q, i) => `${i + 1}. ${q}`).join("\n") }),
    cwd: d.cwd,
    access: "research",
    route,
    schema: schema("research"),
  });
  d.work.saveRaw(`research-${res.harness}.txt`, res.raw);
  const out = res.json as ResearchOutput | undefined;
  if (!out?.answers) throw new Error(`researcher returned no valid result: ${res.text.slice(0, 300)}`);
  const at = new Date().toISOString();
  writeFileSync(join(d.work.dir, "research.md"), renderResearch(out, at));
  writeFileSync(join(d.work.dir, "research.json"), JSON.stringify(out, null, 2) + "\n");
  d.work.log({ step: "research", harness: res.harness, model: res.model, ms: res.ms, cost_usd: res.cost_usd, outcome: out.outcome, questions: d.questions.length, unverified: out.unverified.length });
  return out;
}

export function plan(d: RoleDeps & { request: string }): PlanOutput {
  const route = plannerRoute(d.config, d.tier);
  const researchPath = join(d.work.dir, "research.md");
  const res = d.runner({
    label: "planner",
    prompt: fill(prompt("planner"), { request: d.request || "(not given)", tier: d.tier, research: existsSync(researchPath) ? readFileSync(researchPath, "utf8") : "(none)" }),
    cwd: d.cwd,
    access: "read",
    route,
    schema: schema("plan"),
  });
  d.work.saveRaw(`plan-${res.harness}.txt`, res.raw);
  const out = res.json as PlanOutput | undefined;
  if (!out?.direction) throw new Error(`planner returned no valid plan: ${res.text.slice(0, 300)}`);
  const at = new Date().toISOString();
  writeFileSync(join(d.work.dir, "plan.md"), renderPlan(out, at));
  writeFileSync(join(d.work.dir, "plan.json"), JSON.stringify(out, null, 2) + "\n");
  d.work.log({ step: "plan", harness: res.harness, model: res.model, ms: res.ms, cost_usd: res.cost_usd, outcome: out.outcome, steps: out.steps.length });
  return out;
}
